---
title: "Project 3"
output: html_notebook
---

```{r}
link='https://github.com/SamHenkels47/project3/raw/main/project3excel.xlsx'
mydata=rio::import(link)
mydata
```

```{r}
str(mydata)
```
```{r}
boxplot(mydata[,c('ANNUAL2020','ANNUAL2015','ANNUAL2010')])
```
```{r}
mydata$ANNUAL2020=as.vector(scale(mydata$ANNUAL2020))

```

```{r}
mydata$ANNUAL2010a=as.vector(scale(mydata$ANNUAL2010))
mydata$ANNUAL2015a=as.vector(scale(mydata$ANNUAL2015))
mydata$ANNUAL2020a=as.vector(scale(mydata$ANNUAL2020))

```

```{r}
set.seed(123)

library(cluster)
vars=c('ANNUAL2015a','ANNUAL2010a','ANNUAL2020a') #variables needed

distMatrix=cluster::daisy(mydata[,vars])
          
res.pam=cluster::pam(x=distMatrix,
                     k = 5,
                     cluster.only = F)
```

```{r}
mydata$cluster=as.factor(res.pam$clustering)
```

```{r}
mydata$cluster=factor(mydata$cluster,
                  

levels=c(1,2,3,4,5),
                           labels=c("Largest Export Market","Second Largest Export Market","Major Export Market","Minor Export Market","Little to No Exports"),
                           ordered=T)

```

``` {r}
linkMap="https://github.com/EvansDataScience/VAforPM_Spatial/raw/main/worldMap.geojson" 

library(sf)
```



```{r}
mapWorld=read_sf(linkMap)
```

```{r}
head(mapWorld)
```

```{r}
mapWorldVars=merge(mapWorld, #map first
                   mydata, 
                   by='ISO3') 
```

```{R}
library(ggplot2)
# plot original map
base=ggplot(data=mapWorld) + geom_sf(fill='grey90',
                                     color=NA) + theme_classic()
base
```

```{r}
colMap= base + geom_sf(data=mapWorldVars,
                       aes(fill=ANNUAL2020),
                       color=NA)
colMap
```

```{r}
clusterMap= base + geom_sf(data=mapWorldVars,
                           aes(fill=cluster),
                           color="black",
                           size = 0.005) # color of border
clusterMap 
```


```{r}
Map1 = clusterMap+ scale_fill_brewer(palette ='YlOrRd',
                               direction = -1)

Map1
```

```{R}
titleText='Destination of Exports from Oregon'
sourceText='Source: US Census Bureau'
descriptionText='Export Clasification'
```


```{r}
theLegTitle=" "

Map2 = Map1 + scale_fill_brewer (palette ='YlOrRd',
                              direction = -1, # color order
                              
                              name=theLegTitle)

Map2
```

```{r}

titleText='Destination of Exports from Oregon'
sourceText='Source: US Census Bureau'

Map3 = Map2 + labs(title=titleText,
                     caption = sourceText) 
Map3
```

```{r}
map4 = Map3 + theme(legend.text=element_text(size=7),legend.key.size = unit(0.5, 'cm'))

map4

```

```{r}
saveRDS(map4,file = 'Map1.rds')
saveRDS(map4,file='Map1.rds')

```